# Project information
site_name: 3515.games
site_url: https://3515.games
site_author: celsius narhwal

# Repository
repo_name: celsiusnarhwal/3515.games
repo_url: https://github.com/celsiusnarhwal/3515.games

# Configuration
theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/white-balance-sunny
        name: Step into the light

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/theme-light-dark
        name: Use system theme

    - media: "(prefers-color-scheme: light)"
      scheme: indigo
      toggle:
        icon: material/weather-night
        name: Embrace the dark
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/img/logomark.svg
  logo: assets/img/logomark.svg
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/notes
      tip: material/lightbulb-on
      danger: material/fire

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - social
  - git-committers:
      repository: celsiusnarhwal/3515.games
      branch: main
      enabled: !ENV [MKDOCS_GIT_COMMITTERS, false]

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/celsiusnarhwal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/celsiusnarhwal
    - icon: celsius
      link: https://celsiusnarhwal.dev

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      options:
        custom_icons:
          - docs/.overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: celsiusnarhwal
      repo: 3515.games
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

# Navigation
nav:
  - Home:
      - Home: index.md
  - Games:
      - Rock-Paper-Scissors: games/rps.md
      - UNO: games/uno.md
      - Chess: games/chess.md
      - Cards Against Humanity: games/cah.md
  - Reference: reference.md
  - Legal:
      - Terms of Service: legal/terms.md
      - Privacy Policy: legal/privacy.md
      - Acknowledgements: legal/acknowledgements.md
      - Documentation License: legal/LICENSE.md

# CSS
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/admonitions.css

# JavaScript
extra_javascript:
  - https://kit.fontawesome.com/db4694a70a.js
