# Metadata
site_name: 3515.games
site_url: https://3515.games
site_author: celsius narhwal

# Repository
repo_name: celsiusnarhwal/3515.games
repo_url: https://github.com/celsiusnarhwal/3515.games

# Navigation
nav:
  - Home:
      - Home: index.md
  - Games:
      - Games: games/index.md
      - Rock-Paper-Scissors: games/rps.md
      - UNO: games/uno.md
      - Chess: games/chess.md
      - Cards Against Humanity: games/cah.md
  - Self-Hosting:
      - Self-Hosting: hosting/index.md
      - "Prologue: Heaven and the Earth": hosting/prologue.md
      - "Chapter I: A Secret to Everybody": hosting/i.md
      - "Chapter II: Environmental Activism": hosting/ii.md
      - "Chapter III: Late Registration": hosting/iii.md
      - "Chapter IV: Contain Your Enthusiasm": hosting/iv.md
      - "Chapter V: All Aboard": hosting/v.md
  - Legal:
      - Legal: legal/index.md
      - Terms of Service: legal/terms.md
      - Privacy Policy: legal/privacy.md
      - Acknowledgements: legal/acknowledgements.md
      - Website License: legal/license.md

# Material for MkDocs
theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Step into the light

    - scheme: indigo
      primary: white
      toggle:
        icon: material/weather-night
        name: Embrace the dark
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/img/logomark.svg
  logo: assets/img/logomark.svg
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/notes
      tip: material/lightbulb-on
      danger: material/fire

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - social:
      cards_color:
        fill: "#1e1f22"
        text: white
      cards_font: Poppins
  - typeset
  - git-committers:
      repository: celsiusnarhwal/3515.games
      branch: main

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      options:
        custom_icons:
          - docs/.overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: celsiusnarhwal
      repo: 3515.games
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

# Additional Settings
extra:
  annotate:
    dockerfile: [.s2]
    docker: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/celsiusnarhwal
      name: github.com/celsiusnarhwal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/celsiusnarhwal
      name: "@celsiusnarhwal"
    - icon: fontawesome/solid/envelope
      link: mailto:hello@celsiusnarhwal.dev
    - icon: celsius
      link: https://celsiusnarhwal.dev
      name: celsiusnarhwal.dev

# CSS
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/admonitions.css

# JavaScript
extra_javascript:
  - "https://kit.fontawesome.com/2273b2767b.js"
