[tool.poetry]
name = "games3515"
version = "1.0.0"
description = ""
authors = ["celsiusnarhwal <celsiusnarhwal@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
py-cord = "2.0.0b4"
pip-licenses = "^3.5.3"
toml = "^0.10.2"
llist = "^0.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
