[tool.poetry]
name = "3515.games"
version = "0.0.1"
description = "3515.games is a Discord bot that lets you enjoy real-time social games with your friends."
authors = ["celsiusnarhwal <hello@celsiusnarhwal.dev>"]
packages = [{ include = "kurisu" }]

[tool.poetry.dependencies]
python = "^3.11.1"
alianator = "^3.0.0"
chess = "^1.9.0"
humanize = "^4.0.0"
inflect = "^5.4.0"
jinja2 = "^3.1.2"
jinja2-simple-tags = "^0.4.1"
llist = "^0.7.1"
nltk = "^3.7"
path = "^16.4.0"
pendulum = "^2.1.2"
pony = "^0.7.16"
psycopg2 = "^2.9.3"
py-cord = "^2.1.1"
pydantic = "^1.10.2"
PyGithub = "^1.55"
shortuuid = "^1.0.8"
sortedcontainers = "^2.4.0"
svglib = "^1.4.1"
tomlkit = "^0.11.6"

[tool.poetry.group.dev.dependencies]
doppler-env = "^0.3.0"
gitignorefile = "^1.1.2"
gitpython = "^3.1.29"
inquirerpy = "^0.3.4"
ipython = "^8.7.0"
pip-licenses = "^4.0.3"
ptpython = "^3.0.22"
pyperclip = "^1.8.2"
rich-tracebacks = "^1.2.1"
semver = "^2.13.0"
wonderwords = "^2.2.0"
black = { extras = ["d"], version = "^22.12.0" }
typer = { extras = ["all"], version = "^0.7.0" }

[tool.poetry.scripts]
kurisu = "kurisu.kurisu:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
