[tool.poetry]
name = "3515.games"
version = "0.0.0"
description = "3515.games is a Discord bot that lets you enjoy real-time social games with your friends."
authors = ["celsiusnarhwal <hello@celsiusnarhwal.dev>"]
packages = [{ include = "src/kurisu" }]

[tool.poetry.dependencies]
python = "^3.11.1"
alianator = "^3.2.0"
attrs = "^22.2.0"
chess = "^1.9.0"
dict-deep = "^4.1.2"
humanize = "^4.0.0"
inflect = "^6.0.2"
jinja2 = "^3.1.2"
jinja2-simple-tags = "^0.4.1"
llist = "^0.7.1"
nest-asyncio = "^1.5.6"
nltk = "^3.7"
ordered-set = "^4.1.0"
orjson = "^3.8.6"
path = "^16.4.0"
pendulum = "^2.1.2"
pony = "^0.7.16"
psycopg2 = "^2.9.3"
py-cord = "^2.1.1"
pydantic = "^1.10.2"
PyGithub = "^1.55"
sortedcontainers = "^2.4.0"
svglib = "^1.4.1"
tomlkit = "^0.11.6"

[tool.poetry.group.dev.dependencies]
doppler-env = "^0.3.0"
gitignorefile = "^1.1.2"
gitpython = "^3.1.29"
inquirerpy = "^0.3.4"
ipython = "^8.7.0"
pip-licenses = "^4.0.3"
pyperclip = "^1.8.2"
rich-tracebacks = "^1.2.1"
semver = "^2.13.0"
wonderwords = "^2.2.0"
typer = { extras = ["all"], version = "^0.7.0" }

[tool.poetry.scripts]
kurisu = "src.kurisu.kurisu:app"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.poe.tasks]
format = "pre-commit run black prettier isort --all-files"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
