# Key reference: https://pronoundb.org/docs
# Value reference: https://inflect.readthedocs.io/en/latest/#inflect.engine.gender

hh = ["masculine"]
hi = ["masculine", "neuter"]
hs = ["masculine", "feminine"]
ht = ["masculine", "gender-neutral"]
ih = ["neuter", "masculine"]
ii = ["neuter"]
is = ["neuter", "feminine"]
it = ["neuter", "gender-neutral"]
shh = ["feminine", "masculine"]
sh = ["feminine"]
si = ["feminine", "neuter"]
st = ["feminine", "gender-neutral"]
th = ["gender-neutral", "masculine"]
ti = ["gender-neutral", "neuter"]
ts = ["gender-neutral", "feminine"]
tt = ["gender-neutral"]
any = ["masculine", "neuter", "feminine", "gender-neutral"]
