# Key reference: https://pronoundb.org/docs

hh = ["masculine", "masculine"]
hi = ["masculine", "neuter"]
hs = ["masculine", "feminine"]
ht = ["masculine", "gender-neutral"]
ih = ["neuter", "masculine"]
ii = ["neuter", "neuter"]
is = ["neuter", "feminine"]
it = ["neuter", "gender-neutral"]
shh = ["feminine", "masculine"]
sh = ["feminine", "feminine"]
si = ["feminine", "neuter"]
st = ["feminine", "gender-neutral"]
th = ["gender-neutral", "masculine"]
ti = ["gender-neutral", "neuter"]
ts = ["gender-neutral", "feminine"]
tt = ["gender-neutral", "gender-neutral"]
any = ["masculine", "neuter", "feminine", "gender-neutral"]
