name: Privileged
description: Choose this if you're @celsiusnarhwal or he asked you directly to create an issue here.
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Confirmation
      options:
        - label: I'm @celsiusnarhwal or he asked me directly to create an issue here. I understand that my issue will be closed without comment if neither of these things are true.
          required: true

  - type: textarea
    id: content
    attributes:
      label: Issue
      description: Describe the issue.
