name: Publish Documentation

on:
  push:
    branches:
      - main
      - dev
    paths:
      - docs/**
      - mkdocs.yml
      - pyproject.toml
      - .github/workflows/docs.yml

  workflow_dispatch:

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Set Up Poetry
        run: pipx install poetry==1.4.1 && poetry install --no-root --only ci

      - name: Configure Material Credentials
        run: |
          poetry config repositories.material https://github.com/squidfunk/mkdocs-material-insiders
          poetry config http-basic.material celsiusnarhwal ${{ secrets.MATERIAL_INSIDERS_TOKEN }}

      - name: Save Cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Dependencies
        run: poetry install --no-root --only docs && poe fontawesome
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Build Documentation
        run: poetry run mkdocs build
        env:
          MKDOCS_GIT_COMMITTERS: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: site
          name: site

  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: site

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Documentation
        run: vercel --cwd site ${{ github.ref == 'refs/heads/main' && '--prod' || '' }} --token ${{ secrets.VERCEL_TOKEN }}
