name: Publish Documentation

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml
      - pyproject.toml
      - .github/workflows/docs.yml

  workflow_dispatch:

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Set Up Poetry
        run: pipx install poetry==1.4.1 poethepoet

      - name: Configure Material Credentials
        run: |
          poetry config repositories.material https://github.com/squidfunk/mkdocs-material-insiders
          poetry config http-basic.material celsiusnarhwal ${{ secrets.MATERIAL_INSIDERS_TOKEN }}

      - name: Save Cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}

      - name: Build Documentation
        run: poetry install --only docs && poe fontawesome && poetry run mkdocs build
        env:
          MKDOCS_GIT_COMMITTERS: true
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
