name: Publish Documentation

on:
  push:
    branches:
      - main
      - dev
    paths:
      - docs/**
      - mkdocs.yml
      - pyproject.toml
      - .github/workflows/docs.yml

  workflow_dispatch:

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Set Up Poetry
        run: pipx install poetry==1.4.1 && pipx install poethepoet

      - name: Configure Material Credentials
        run: |
          poetry config repositories.material https://github.com/squidfunk/mkdocs-material-insiders
          poetry config http-basic.material celsiusnarhwal ${{ secrets.MATERIAL_INSIDERS_TOKEN }}

      - name: Save Cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Dependencies
        run: poetry install --no-root --only docs && poe fontawesome
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Build Documentation
        run: poetry run mkdocs build
        env:
          MKDOCS_GIT_COMMITTERS: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}

      - name: Upload Artifact (Production)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

      - name: Upload Artifact (Preview)
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: actions/upload-artifact@v3
        with:
          path: site
          name: site

  deploy-prod:
    name: Deploy Documentation
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

  deploy-preview:
    name: Deploy Preview Documentation
    if: ${{ github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: site

      - name: Deploy to Vercel
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: vercel
          FOLDER: site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
