name: Merge PRs
on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  celsiusnarhwal:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.actor == 'celsiusnarhwal' && github.event.label.name == 'privileged' }}
    steps:
      - name: Get Token
        id: nodoka
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.NODOKA_ID }}
          private_key: ${{ secrets.NODOKA_PASSWORD }}
          permissions: >-
            {
              "pull_requests": "write"
            }

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge PR
        run: gh pr merge --auto --merge ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ steps.nodoka.outputs.token }}

  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get PR Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Merge PR
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --merge ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Flag PR
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-major' }}
        run: "gh pr edit --add-assignee celsiusnarhwal --add-reviewer celsiusnarhwal ${{ github.event.pull_request.number }}"

  other:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'celsiusnarhwal' }}
    steps:
      - name: Get User Type
        id: user
        run: echo "type=$(gh api users/${{ github.actor }} --jq '.type')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Close PR
        if: ${{ steps.user.outputs.type != 'User' }}
        run: gh pr close ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ github.token }}
