on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Install pre-commit
        run: pipx install pre-commit

      - name: Update Hooks
        run: pre-commit autoupdate

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 3515.games
          commit-message: Update pre-commit hooks
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: Update pre-commit hooks
          branch: 3515.games/pre-commit-autoupdate
          delete-branch: true
          assignees: celsiusnarhwal
          reviewers: celsiusnarhwal
