on:
  issues:
    types:
      - opened

jobs:
  check-privilege:
    name: Check Privilege
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        if: ${{ github.event.label.name == 'privileged' && github.actor != 'celsiusnarhwal' }}
        run: gh issue close ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ github.token }}
